name: "godot-ci export"
on:
  push:
    tags: [ "v*" ]
env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: "."
  R2_BUCKET_NAME: games/gamball

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html" -- --version=${{ github.ref_name }}
      - name: Retrieve the secret and decode it to a file
        env:
          RCLONE_CONFIG_BASE64: ${{ secrets.RCLONE_CONFIG_BASE64 }}
        run: |
          mkdir -v -p ~/.config/rclone/
          echo ${RCLONE_CONFIG_BASE64} | base64 --decode > ~/.config/rclone/rclone.conf
      - name: Install rclone
        run: |
          apt-get update && apt-get install -y curl
          curl https://rclone.org/install.sh | bash
      - name: Deploy to Cloudflare R2
        run: |
          rclone copy build/web r2:${R2_BUCKET_NAME}/
          rclone tree r2:${R2_BUCKET_NAME}/
